services:
  app:
    build:
      context: ./build/laravel
      dockerfile: Dockerfile
    environment:
      - REPO_URL=https://github.com/mbezuidenhout/pp-test.git
      - TZ=${TZ:-Africa/Johannesburg}
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=${DB_DATABASE:-laravel}
      - DB_USERNAME=${DB_DATABASE:-laravel}
      - DB_PASSWORD=${DB_PASSWORD:-laravel}
      - MAIL_MAILER=smtp
      - MAIL_SCHEME=null
      - MAIL_HOST=mailhog
      - MAIL_PORT=1025
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./app:/var/www
      - ./app-entrypoint.d/:/docker/entrypoint.d/
    depends_on:
      db:
        condition: service_started
    networks:
      - backend
    env_file:
      - .env

  queue:
    profiles: ["staging"]
    build:
      context: ./build/laravel
      dockerfile: Dockerfile
    command: php artisan queue:work --verbose --tries=3 --timeout=90
    restart: unless-stopped
    environment:
      - TZ=${TZ:-Africa/Johannesburg}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./app:/var/www
    depends_on:
      db:
        condition: service_started
    networks:
      - backend
    env_file:
      - .env
  nginx:
    build:
      context: ./build/nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
    environment:
      - TZ=${TZ:-Africa/Johannesburg}
    volumes:
      - ./app:/var/www
      - ./etc/nginx/app.conf:/etc/nginx/conf.d/app.conf
      - ./etc/nginx/ssl:/etc/nginx/ssl
    depends_on:
      app:
        condition: service_started
    networks:
      - frontend
      - backend
  db:
    image: mariadb
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      - TZ=${TZ:-Africa/Johannesburg}
      - MARIADB_DATABASE=${DB_DATABASE:-laravel}
      - MARIADB_USER=${DB_USERNAME:-laravel}
      - MARIADB_PASSWORD=${DB_PASSWORD:-laravel}
      - MARIADB_RANDOM_ROOT_PASSWORD=true
    volumes:
      - ./db:/var/lib/mysql
    networks:
      - backend
  mailhog:
    profiles: ["dev", "staging"]
    image: bezuidenhout/mailhog # Rebuild of mailhog to run on arm64 and other platforms
    restart: always
    ports:
      - '8025:8025' # web ui
    environment:
      - TZ=${TZ:-Africa/Johannesburg}
    networks:
      - backend
      - frontend

volumes:
  mariadb_data:

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
