name: Static Application Security Testing

run-name: ${{ github.actor }} run SAST

on:
  push:
    branches: [ develop, main ]

jobs:
  sast-tests:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: app

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Run composer install
        run: composer install -n --prefer-dist

      - name: Run ESLint
        run: npx eslint resources/js

      - name: Run npm audit
        run: npm audit


