name: Static Code Analysis

run-name: ${{ github.actor }} run SCA

on:
  push:
    branches: [ develop ]

jobs:
  sca-tests:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: app

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Run composer install
        run: composer install -n --prefer-dist

      - uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run pint code styling test
        run: ./vendor/bin/pint --test

      - name: Install NPM dependencies
        run: npm ci

      - name: Run ESLint
        run: npx eslint resources/js